project:
  type: website
  title: "Modelos Probabilistas en C"
  
website:
  title: "Modelos Probabilistas en C"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proyecto-modelos-probabilistas.qmd
        text: Documentación
    right:
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto
